In [16]:
import pandas as pd
import json

In [3]:
pd.read_json("darko_raw.json")

,age,box_ddpm,box_odpm,d_dpm,d_dpm_rank,dpm,dpm_rank,nba_id,o_dpm,o_dpm_rank,on_off_ddpm,on_off_odpm,player_name,season,team_name,tm_id
0,36.1,-0.35,1.49,-0.60,299,0.46,71,2,1.06,50,-1.08,-0.34,Byron Scott,1997,Los Angeles Lakers,1610612747
1,31.1,-0.17,-0.89,-0.14,162,-0.99,179,3,-0.85,206,-0.06,-0.65,Grant Long,1997,Detroit Pistons,1610612765
2,38.0,-0.49,-2.36,-0.47,256,-2.90,406,7,-2.43,388,-0.33,-3.06,Dan Schayes,1997,Orlando Magic,1610612753
3,35.7,-0.54,-1.44,-0.53,275,-2.02,302,9,-1.49,284,-0.44,-1.95,Sedale Threatt,1997,Houston Rockets,1610612745
4,27.3,-0.52,-1.22,-0.52,273,-1.72,263,12,-1.19,242,-0.57,-0.95,Chris King,1997,Miami Heat,1610612748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15019,24.2,0.90,-1.87,0.89,104,-0.97,308,1643024,-1.87,535,-0.24,-1.73,Chris Mañon,2026,Los Angeles Lakers,1610612747
15020,23.9,-0.36,-2.27,-0.36,414,-2.63,615,1643047,-2.27,612,-0.88,-1.84,CJ Huntley,2026,Phoenix Suns,1610612756
15021,23.7,-0.09,-1.73,-0.09,316,-1.83,478,1643052,-1.73,500,-0.77,-1.77,Chaney Johnson,2026,Brooklyn Nets,1610612751
15022,22.8,-0.33,-3.06,-0.34,409,-3.39,666,1643133,-3.06,664,-0.54,-2.18,Lawson Lovering,2026,Memphis Grizzlies,1610612763
15023,24.6,-0.43,-2.00,-0.43,449,-2.44,595,1643141,-2.00,571,-0.57,-1.94,Jahmyl Telfort,2026,Los Angeles Clippers,1610612746

In [4]:
pd.read_json("raptor_raw.json")

,d_raptor_rank,mp,nba_id,o_raptor_rank,player_id,player_name,poss,raptor_defense,raptor_offense,raptor_rank,raptor_total,season,war_total
0,131,959,abdelal01,220,abdelal01,Alaa Abdelnaby,1998,-0.2,-2.6,210,-2.8,1992,-0.006893
1,256,1379,abdelal01,225,abdelal01,Alaa Abdelnaby,2754,-2.1,-2.4,251,-4.4,1993,-1.227189
2,4,3483,abdulka01,1,abdulka01,Kareem Abdul-Jabbar,7674,3.1,4.5,1,7.6,1977,18.488255
3,3,2399,abdulka01,6,abdulka01,Kareem Abdul-Jabbar,5343,3.4,3.4,1,6.9,1978,11.688727
4,8,3524,abdulka01,10,abdulka01,Kareem Abdul-Jabbar,7826,2.5,3.0,1,5.5,1979,14.739138
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12495,212,1082,1627790,269,zizican01,Ante Zizic,2240,-0.7,-2.1,272,-2.8,2019,-0.007877
12496,49,1079,1627826,281,zubaciv01,Ivica Zubac,2345,1.8,-2.4,167,-0.6,2019,1.217134
12497,12,1646,1627826,76,zubaciv01,Ivica Zubac,3447,3.6,1.1,18,4.6,2020,6.224207
12498,32,1910,1627826,205,zubaciv01,Ivica Zubac,3908,2.5,-0.9,95,1.6,2021,4.261327
12499,115,1852,1627826,200,zubaciv01,Ivica Zubac,3786,0.7,-0.7,161,0.0,2022,2.626958

In [17]:
with open("wingspans.json", "r") as f:
    data = json.load(f)

# Save just the rows as a new JSON file
with open("wingspans.json", "w") as f:
    json.dump(data["rows"], f, indent=2)

TypeError: list indices must be integers or slices, not str

In [7]:
df = pd.read_json("wingspans.json")
df

,active,d_dpm,height_wingspan_diff_in,height_wo_shoes_in,nba_id,player,pos2,primary_pos,team,wingspan_in
0,False,NaN,6.00,70.00,201166,Aaron Brooks,PG,PG,None,76.00
1,False,NaN,1.25,72.75,203905,Aaron Craft,UNK,UNK,None,74.00
2,True,0.44,4.25,79.50,203932,Aaron Gordon,PF,PF,DEN,83.75
3,False,NaN,3.25,84.00,201189,Aaron Gray,C,C,None,87.25
4,False,NaN,3.75,76.50,1626151,Aaron Harrison,SG,SG,None,80.25
...,...,...,...,...,...,...,...,...,...,...
1830,True,0.50,4.75,81.25,1630192,Zeke Nnaji,PF,PF,DEN,86.00
1831,False,NaN,7.00,74.75,1629015,Zhaire Smith,SF,SF,None,81.75
1832,False,NaN,6.50,85.25,1627753,Zhou Qi,C,C,None,91.75
1833,True,0.54,2.00,80.25,1630533,Ziaire Williams,SF,SF,BKN,82.25
1834,True,-0.78,4.75,78.00,1629627,Zion Williamson,C,C,NOP,82.75

In [15]:
df=df[["player","wingspan_in", "height_wo_shoes_in", "height_wingspan_diff_in"]].dropna()
df=df.rename(columns={"player":"Player"})

KeyError: "['player'] not in index"

In [14]:
df.to_csv("bruh.csv", index=False)